valuesFilePath: ./values.yaml
resources:
  - name: {{ .Values.var.gitRepoResource }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.var.gitProvider }}
      path: {{ .Values.var.path }}
      branches:
        include: {{ .Values.var.branches }}
  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.var.artifactory }}
      buildName: {{ .Values.var.pipelineName }}
      buildNumber: ${run_number}

pipelines:
  - name: {{ .Values.var.pipelineName }}
    preRun:
      execution:
        onExecute:
          - echo "Executing Pre Run"
          #- update_run_description "Custom Triggered by $step_triggered_by_identity_name"
    postRun:
      execution:
        onExecute:
          - echo "Executing Post Run"
          - set_run_name "v$run_number.0"
    configuration:
      nodePool: default-dynamic-nodepool
      jfrogCliVersion: 2
    steps:
      - name: sample_step
        type: Bash
        configuration: 
          inputResources:
           - name: {{ .Values.var.gitRepoResource }}
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"
      
      - name: mvn_build
        type: MvnBuild
        configuration:
          inputSteps:
            - name: sample_step
          integrations:
            - name: {{ .Values.var.artifactory }}
          inputResources:
            - name: {{ .Values.var.gitRepoResource }}
          outputResources:
            - name: mvn_build_info
          mvnCommand: clean install
          forceXrayScan: false
          failOnScan: false
          autoPublishBuildInfo: true
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - curl -fL https://install-cli.jfrog.io | sh
            - jf --version
            - task: jfrog/docker-build@v0.0.1
              input:
                gitRepoResource: {{ .Values.var.gitRepoResource }}
                dockerImage: "{{ .Values.var.jfrogPlatformInstance }}/{{ .Values.var.dockerRepoName }}/{{ .Values.var.pipelineName }}:${run_number}"
                dockerFileName: Dockerfile
            - task: jfrog/docker-push@v0.0.2
              input:
                dockerImage: "{{ .Values.var.jfrogPlatformInstance }}/{{ .Values.var.dockerRepoName }}/{{ .Values.var.pipelineName }}:${run_number}"
                xrayScan: "false"
                failOnScan: "false"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"
            - save_tests $res_{{ .Values.var.gitRepoResource }}_resourcePath/target/surefire-reports/
